defaults: &DEFAULTS
  socketio_uri: http://localhost:9999/
  login_url: http://localhost:3000/users/sign_in
  logout_url: http://localhost:3000/users/sign_out
  signup_url: http://localhost:3000/users/sign_up
  api_auth_token: 'M9812Y125T-V234BCOV6-B7PGL23WM-S68CAS53FNGO2B-4JGNT-6RU'
  main_app_url: http://localhost:3000/
  store_url: http://localhost:5000/
  store_api_url: http://localhost:5000/private/api/
  store_api_auth_token: 'M9812Y125T-V234BCOV6-B7PGL23WM-S68CAS53FNGO2B-4JGNT-6RU'
  forum_url: http://localhost:4000/
  forum_api_url: http://localhost:4000/private/api/
  forum_api_auth_token: 'M9812Y125T-V234BCOV6-B7PGL23WM-S68CAS53FNGO2B-4JGNT-6RU'

development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
  socketio_uri: http://dev.pointgaming.com:4000/
  login_url: http://dev.pointgaming.com/users/sign_in
  logout_url: http://dev.pointgaming.com/users/sign_out
  signup_url: http://dev.pointgaming.com/users/sign_up
  api_auth_token: '25ds-45p56q63-56b75s5m-ndma2fd86gkjo4n6-5124z5568-68f9s'
  main_app_url: http://www.pointgaming.com/
  store_url: http://store.pointgaming.com/
  store_api_url: http://store.pointgaming.com/private/api/
  store_api_auth_token: '25ds-45p56q63-56b75s5m-ndma2fd86gkjo4n6-5124z5568-68f9s'
  forum_url: http://forums.pointgaming.com/
  forum_api_url: http://forums.pointgaming.com/private/api/
  forum_api_auth_token: '25ds-45p56q63-56b75s5m-ndma2fd86gkjo4n6-5124z5568-68f9s'
